schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "blue_genes"
version = "1.0.1"
name = "Blue Genes"
tagline = "A dark blue theme with larger vertices and edges"
maintainer = "Spectral Vectors"
# Supported types: "add-on", "theme"
type = "theme"

# Optional link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Dark", "Colorful"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]
